name: Upstream utils

on:
  pull_request:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  update:
    strategy:
      fail-fast: false
      matrix:
        include:
        - { os: windows-2022, python_cmd: "py" }
        - { os: ubuntu-22.04, python_cmd: "" }
        - { os: macos-14,     python_cmd: "" }

    name: "Update"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch all history and metadata
        run: |
          git checkout -b pr
          git branch -f main origin/main
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Configure committer identity
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Run eigen.py
        run: |
          cd upstream_utils
          ${{ matrix.python_cmd }} ./eigen.py clone
          ${{ matrix.python_cmd }} ./eigen.py copy-upstream-to-thirdparty
      - name: Run expected.py
        run: |
          cd upstream_utils
          ${{ matrix.python_cmd }} ./expected.py clone
          ${{ matrix.python_cmd }} ./expected.py copy-upstream-to-thirdparty
      - name: Run fmt.py
        run: |
          cd upstream_utils
          ${{ matrix.python_cmd }} ./fmt.py clone
          ${{ matrix.python_cmd }} ./fmt.py copy-upstream-to-thirdparty
      - name: Run gcem.py
        run: |
          cd upstream_utils
          ${{ matrix.python_cmd }} ./gcem.py clone
          ${{ matrix.python_cmd }} ./gcem.py copy-upstream-to-thirdparty
      - name: Run json.py
        run: |
          cd upstream_utils
          ${{ matrix.python_cmd }} ./json.py clone
          ${{ matrix.python_cmd }} ./json.py copy-upstream-to-thirdparty
      - name: Run libuv.py
        run: |
          cd upstream_utils
          ${{ matrix.python_cmd }} ./libuv.py clone
          ${{ matrix.python_cmd }} ./libuv.py copy-upstream-to-thirdparty
      - name: Run llvm.py
        run: |
          cd upstream_utils
          ${{ matrix.python_cmd }} ./llvm.py clone
          ${{ matrix.python_cmd }} ./llvm.py copy-upstream-to-thirdparty
      - name: Run mpack.py
        run: |
          cd upstream_utils
          ${{ matrix.python_cmd }} ./mpack.py clone
          ${{ matrix.python_cmd }} ./mpack.py copy-upstream-to-thirdparty
      - name: Run stack_walker.py
        run: |
          cd upstream_utils
          ${{ matrix.python_cmd }} ./stack_walker.py clone
          ${{ matrix.python_cmd }} ./stack_walker.py copy-upstream-to-thirdparty
      - name: Run memory.py
        run: |
          cd upstream_utils
          ${{ matrix.python_cmd }} ./memory.py clone
          ${{ matrix.python_cmd }} ./memory.py copy-upstream-to-thirdparty
      - name: Run protobuf.py
        run: |
          cd upstream_utils
          ${{ matrix.python_cmd }} ./protobuf.py clone
          ${{ matrix.python_cmd }} ./protobuf.py copy-upstream-to-thirdparty
      - name: Run sleipnir.py
        run: |
          cd upstream_utils
          ${{ matrix.python_cmd }} ./sleipnir.py clone
          ${{ matrix.python_cmd }} ./sleipnir.py copy-upstream-to-thirdparty
      - name: Add untracked files to index so they count as changes
        run: git add -A
      - name: Check output
        run: git --no-pager diff --exit-code HEAD
